// Mock data for the application

export const accessories = [
  {
    id: "1",
    name: "Sterile Surgical Gloves",
    description: "High-quality latex surgical gloves with superior grip and protection.",
    price: 14.99,
    stock: 100,
    category: "Protective Gear",
    image: "https://i.ytimg.com/vi/BcYpQRWT7NA/maxresdefault.jpg",
  },
  {
    id: "2",
    name: "Scalpel Blades (Pack of 10)",
    description: "Precision stainless steel scalpel blades for surgical procedures.",
    price: 9.99,
    stock: 200,
    category: "Surgical Instruments",
    image: "https://tse1.mm.bing.net/th?id=OIP.2mnGjXf3s17MaXUi1mYV7wHaFR&pid=Api&P=0&h=220",
  },
  {
    id: "3",
    name: "Surgical Face Mask",
    description: "3-layer disposable face mask with high filtration efficiency.",
    price: 5.99,
    stock: 500,
    category: "Protective Gear",
    image: "https://tse2.mm.bing.net/th?id=OIP.cKoUecnMwTxyDPMcAzyT_QHaHa&pid=Api&P=0&h=220",
  },
  {
    id: "4",
    name: "Disposable Surgical Gown",
    description: "Sterile, fluid-resistant gown for infection control in surgeries.",
    price: 24.99,
    stock: 150,
    category: "Protective Gear",
    image: "https://tse3.mm.bing.net/th?id=OIP.p-XSqJWC3w0bdr0ozBixwgHaGc&pid=Api&P=0&h=220",
  },
  {
    id: "5",
    name: "Surgical Sutures (Pack of 12)",
    description: "High-quality absorbable sutures for wound closure.",
    price: 29.99,
    stock: 80,
    category: "Wound Care",
    image: "https://tse2.mm.bing.net/th?id=OIP.B74skQK3LWYyHoEYek02ywHaCU&pid=Api&P=0&h=220",
  },
  {
    id: "6",
    name: "Surgical Forceps",
    description: "Stainless steel forceps for precision handling during surgery.",
    price: 19.99,
    stock: 120,
    category: "Surgical Instruments",
    image: "https://tse4.mm.bing.net/th?id=OIP.qGVlGNBUJRAq0jPeSrJfJAHaED&pid=Api&P=0&h=220",
  },
  {
    id: "7",
    name: "Autoclave Sterilization Pouches",
    description: "Self-sealing sterilization pouches for safe instrument storage.",
    price: 12.99,
    stock: 300,
    category: "Sterilization",
    image: "https://image.made-in-china.com/2f0j00SCAlyBjkpgrM/Medical-Autoclave-Steam-Sterilization-Pouches-Roll-for-Hospital-Dental-Use.jpg",
  },
  {
    id: "8",
    name: "Surgical Headlamp",
    description: "Bright LED surgical headlamp for enhanced visibility during procedures.",
    price: 49.99,
    stock: 50,
    category: "Surgical Equipment",
    image: "https://tse3.mm.bing.net/th?id=OIP.mQdPE6f7IITNPzGakVYKAQHaHv&pid=Api&P=0&h=220",
  },
  {
    id: "9",
    name: "Medical Cotton Rolls",
    description: "High-absorbency medical cotton rolls for wound dressing.",
    price: 8.99,
    stock: 400,
    category: "Wound Care",
    image: "https://tse4.mm.bing.net/th?id=OIP.Z-JSQRNhbvv7LkL4clIEBgHaCt&pid=Api&P=0&h=220",
  },
]

export const users = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    joinDate: "01/15/2023",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "Customer",
    joinDate: "02/20/2023",
  },
  {
    id: "3",
    name: "Robert Johnson",
    email: "robert@example.com",
    role: "Customer",
    joinDate: "03/10/2023",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily@example.com",
    role: "Customer",
    joinDate: "04/05/2023",
  },
  {
    id: "5",
    name: "Michael Wilson",
    email: "michael@example.com",
    role: "Admin",
    joinDate: "05/12/2023",
  },
]

export const contactMessages = [
  {
    id: "1",
    name: "Sarah Thompson",
    email: "sarah@example.com",
    subject: "Product Inquiry",
    message:
      "I'm interested in the wireless earbuds but I have a question about the battery life. Can you provide more details?",
    date: "06/10/2023",
    status: "New",
  },
  {
    id: "2",
    name: "David Brown",
    email: "david@example.com",
    subject: "Order Status",
    message:
      "I placed an order three days ago (Order #12345) and haven't received any shipping confirmation. Could you please check the status?",
    date: "06/15/2023",
    status: "New",
  },
  {
    id: "3",
    name: "Lisa Martinez",
    email: "lisa@example.com",
    subject: "Return Request",
    message: "I received a damaged phone case and would like to return it. What is the return process?",
    date: "06/20/2023",
    status: "Responded",
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james@example.com",
    subject: "Product Suggestion",
    message:
      "I would love to see more options for tablet accessories in your store. Do you have plans to expand your product range?",
    date: "06/25/2023",
    status: "Responded",
  },
  {
    id: "5",
    name: "Amanda Garcia",
    email: "amanda@example.com",
    subject: "Website Feedback",
    message:
      "I really like your website design, but I noticed that the checkout process could be improved. Sometimes it takes too long to load the payment page.",
    date: "06/30/2023",
    status: "New",
  },
]

// Mock orders data
export const orders = [
  {
    id: "ORD-001",
    customerName: "Alex Johnson",
    company: "Tech Solutions Inc.",
    email: "alex@example.com",
    phone: "123-456-7890",
    address: "123 Main St, Anytown, AT 12345",
    purchaseOrderNumber: "PO-12345",
    additionalInfo: "Please deliver to the loading dock at the back of the building.",
    items: [
      { id: "1", name: "Premium Phone Case", price: 19.99, quantity: 2 },
      { id: "3", name: "Wireless Earbuds", price: 49.99, quantity: 1 },
    ],
    total: 89.97,
    status: "Pending",
    date: "07/15/2023",
  },
  {
    id: "ORD-002",
    customerName: "Maria Garcia",
    company: "Garcia Enterprises",
    email: "maria@example.com",
    phone: "234-567-8901",
    address: "456 Oak Ave, Somewhere, SW 23456",
    purchaseOrderNumber: "PO-67890",
    additionalInfo: "",
    items: [
      { id: "2", name: "Fast Charging Cable", price: 12.99, quantity: 3 },
      { id: "4", name: "Power Bank 10000mAh", price: 29.99, quantity: 1 },
      { id: "5", name: "Screen Protector", price: 9.99, quantity: 2 },
    ],
    total: 75.95,
    status: "Payment Received",
    date: "07/18/2023",
  },
  {
    id: "ORD-003",
    customerName: "Thomas Wilson",
    company: "Wilson & Sons",
    email: "thomas@example.com",
    phone: "345-678-9012",
    address: "789 Pine Rd, Elsewhere, EW 34567",
    purchaseOrderNumber: "",
    additionalInfo: "Call before delivery",
    items: [{ id: "8", name: "Bluetooth Speaker", price: 39.99, quantity: 1 }],
    total: 39.99,
    status: "Canceled",
    date: "07/20/2023",
  },
  {
    id: "ORD-004",
    customerName: "Sophia Lee",
    company: "Lee's Electronics",
    email: "sophia@example.com",
    phone: "456-789-0123",
    address: "101 Maple Dr, Nowhere, NW 45678",
    purchaseOrderNumber: "PO-24680",
    additionalInfo: "",
    items: [
      { id: "6", name: "Phone Stand", price: 14.99, quantity: 1 },
      { id: "7", name: "Car Phone Mount", price: 24.99, quantity: 1 },
      { id: "9", name: "Wireless Charger", price: 22.99, quantity: 1 },
    ],
    total: 62.97,
    status: "Pending",
    date: "07/22/2023",
  },
  {
    id: "ORD-005",
    customerName: "Daniel Brown",
    company: "Brown's Mobile Shop",
    email: "daniel@example.com",
    phone: "567-890-1234",
    address: "202 Cedar Ln, Anyplace, AP 56789",
    purchaseOrderNumber: "PO-13579",
    additionalInfo: "This is a rush order, please expedite if possible.",
    items: [
      { id: "1", name: "Premium Phone Case", price: 19.99, quantity: 1 },
      { id: "5", name: "Screen Protector", price: 9.99, quantity: 1 },
    ],
    total: 29.98,
    status: "Payment Received",
    date: "07/25/2023",
  },
]

